name: smos-sync-client-gen
version: '0.0.0.0'
category: Smos
author: Tom Sydney Kerckhove
maintainer: syd@cs-syd.eu
copyright: ! 'Copyright: (c) 2019 Tom Sydney Kerckhove'
license: MIT
homepage: https://github.com/NorfairKing/smos

dependencies:
- base

library:
  source-dirs: src/
  ghc-options: -Wall
  dependencies:
  - QuickCheck
  - async
  - bytestring
  - containers
  - genvalidity
  - genvalidity-hspec
  - hspec
  - hspec-core
  - http-client
  - mergeful
  - mergeful
  - microlens
  - monad-logger
  - pantry
  - path
  - path-io
  - persistent
  - persistent-sqlite
  - resource-pool
  - servant-client
  - smos-api
  - smos-api-gen
  - smos-client
  - smos-server-gen
  - smos-sync-client
  - stm
  - typed-uuid
  - uuid
  - wai
  - warp

tests:
  smos-sync-client-test:
    main: Spec.hs
    source-dirs: test/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - hashable
    - async
    - bytestring
    - containers
    - genvalidity
    - genvalidity-hspec
    - genvalidity-hspec-aeson
    - genvalidity-hspec-optics
    - hspec
    - hspec-core
    - mergeful
    - mergeful
    - monad-logger
    - mtl
    - pantry
    - path
    - path-io
    - persistent
    - persistent-sqlite
    - pretty-show
    - resource-pool
    - servant-auth-client
    - servant-client
    - smos-api
    - smos-client
    - smos-client-gen
    - smos-report
    - smos-server
    - smos-server-gen
    - smos-sync-client
    - smos-sync-client-gen
    - text
    - uuid

benchmarks:
  smos-sync-client-bench:
    main: Bench.hs
    source-dirs: bench/
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    - -Wall
    dependencies:
    - QuickCheck
    - criterion
    - genvalidity-criterion
    - smos-api
    - smos-client
    - smos-client-gen
    - smos-report
    - smos-server
    - smos-server-gen
    - smos-sync-client
    - smos-sync-client-gen
